#SPDX-License-Identifier: MIT-0
---

- name: Check UFW is present
  ansible.builtin.apt:
    name: "ufw"
    state: present

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
  become: true

- name: Limit simultaneous SSH connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: true

- name: Allow SSH only from trusted networks
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
    direction: in
    from_ip: "{{ item }}"
  loop: "{{ baseline_hardening_ssh_allowed_networks }}"
  loop_control:
    label: "{{ item }}"
  become: true

- name: Set default incoming policy to deny
  community.general.ufw:
    default: deny
    direction: incoming
  become: true

- name: Set default outgoing policy to allow
  community.general.ufw:
    default: allow
    direction: outgoing
  become: true

- block:
    - name: Run devsec os hardening
      ansible.builtin.include_role:
        name: devsec.hardening.os_hardening
  become: true

