#SPDX-License-Identifier: MIT-0
---
# tasks file for baseline_hardening
- block:
    - name: Run devsec os hardening
      ansible.builtin.include_role:
        name: devsec.hardening.os_hardening

  become: true