#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/podman_setup

- name: Run container
  containers.podman.podman_container:
    name: web-test
    image: docker.io/crccheck/hello-world
    state: started
    ports:
      - "60001:8000"
