#- name: Installiere Basiskonfiguration
#  hosts: syshard
#  become_method: su
#  become: yes
#  become_user: root

- name: "SYSHARD - Debian 12.11 (netinst)"
  hosts: all
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - preparation
    - podman_setup
    - baseline_hardening
    - ssh_hardening
    - security_updates_management
