#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/ssh_hardening
- block:
    - name: Run devsec ssh hardening
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening

  become: true